/*
 * Musicshop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.1
 * Contact: techsupport@musicshop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {MediumDTO} from '../model/MediumDTO';
import {ShoppingCartDTO} from '../model/ShoppingCartDTO';

/**
* Default service.
* @module api/DefaultApi
* @version 3.0.1
*/
export class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the addToShoppingCart operation.
     * @callback moduleapi/DefaultApi~addToShoppingCartCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:model/MediumDTO} opts.body 
     * @param {String} opts.userId 
     * @param {Number} opts.amount 
     * @param {module:api/DefaultApi~addToShoppingCartCallback} callback The callback function, accepting three arguments: error, data, response
     */
    addToShoppingCart(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        'userId': opts['userId'],'amount': opts['amount']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['text/json'];
      let accepts = ['*/*'];
      let returnType = null;

      return this.apiClient.callApi(
        '/rest/shoppingcart/add', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the buyFromShoppingCart operation.
     * @callback moduleapi/DefaultApi~buyFromShoppingCartCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.userId 
     * @param {Number} opts.id 
     * @param {module:api/DefaultApi~buyFromShoppingCartCallback} callback The callback function, accepting three arguments: error, data, response
     */
    buyFromShoppingCart(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'userId': opts['userId'],'id': opts['id']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/json'];
      let returnType = null;

      return this.apiClient.callApi(
        '/rest/shoppingcart/buy', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the emptyShoppingCart operation.
     * @callback moduleapi/DefaultApi~emptyShoppingCartCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.userId 
     * @param {module:api/DefaultApi~emptyShoppingCartCallback} callback The callback function, accepting three arguments: error, data, response
     */
    emptyShoppingCart(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'userId': opts['userId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;

      return this.apiClient.callApi(
        '/rest/shoppingcart/empty', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getShoppingCart operation.
     * @callback moduleapi/DefaultApi~getShoppingCartCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ShoppingCartDTO{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.userId 
     * @param {module:api/DefaultApi~getShoppingCartCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getShoppingCart(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'userId': opts['userId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/json'];
      let returnType = ShoppingCartDTO;

      return this.apiClient.callApi(
        '/rest/shoppingcart/get', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the removeFromShoppingCart operation.
     * @callback moduleapi/DefaultApi~removeFromShoppingCartCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:model/MediumDTO} opts.body 
     * @param {String} opts.userId 
     * @param {Number} opts.amount 
     * @param {module:api/DefaultApi~removeFromShoppingCartCallback} callback The callback function, accepting three arguments: error, data, response
     */
    removeFromShoppingCart(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        'userId': opts['userId'],'amount': opts['amount']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['text/json'];
      let accepts = ['*/*'];
      let returnType = null;

      return this.apiClient.callApi(
        '/rest/shoppingcart/remove', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the searchArticlesByAttributes operation.
     * @callback moduleapi/DefaultApi~searchArticlesByAttributesCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Search Articles
     * Search Articles by Attributes (Title, Artist)
     * @param {Object} opts Optional parameters
     * @param {String} opts.title 
     * @param {String} opts.artist 
     * @param {module:api/DefaultApi~searchArticlesByAttributesCallback} callback The callback function, accepting three arguments: error, data, response
     */
    searchArticlesByAttributes(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'title': opts['title'],'artist': opts['artist']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/rest/article/search', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}