/*
 * Musicshop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.1
 * Contact: techsupport@musicshop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {AddToShoppingCartForm} from './model/AddToShoppingCartForm';
import {AlbumDTO} from './model/AlbumDTO';
import {ArticleDTO} from './model/ArticleDTO';
import {ArtistDTO} from './model/ArtistDTO';
import {BuyFromShoppingCartForm} from './model/BuyFromShoppingCartForm';
import {Credentials} from './model/Credentials';
import {InvoiceDTO} from './model/InvoiceDTO';
import {LineItemDTO} from './model/LineItemDTO';
import {MediumDTO} from './model/MediumDTO';
import {RemoveFromShoppingCartForm} from './model/RemoveFromShoppingCartForm';
import {ShoppingCartDTO} from './model/ShoppingCartDTO';
import {SongDTO} from './model/SongDTO';
import {SongDTOLength} from './model/SongDTOLength';
import {SongDTOLengthDuration} from './model/SongDTOLengthDuration';
import {SongDTOLengthUnits} from './model/SongDTOLengthUnits';
import {SupplierDTO} from './model/SupplierDTO';
import {DefaultApi} from './api/DefaultApi';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MusicshopApi = require('index'); // See note below*.
* var xxxSvc = new MusicshopApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MusicshopApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MusicshopApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MusicshopApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 3.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddToShoppingCartForm model constructor.
     * @property {module:model/AddToShoppingCartForm}
     */
    AddToShoppingCartForm,

    /**
     * The AlbumDTO model constructor.
     * @property {module:model/AlbumDTO}
     */
    AlbumDTO,

    /**
     * The ArticleDTO model constructor.
     * @property {module:model/ArticleDTO}
     */
    ArticleDTO,

    /**
     * The ArtistDTO model constructor.
     * @property {module:model/ArtistDTO}
     */
    ArtistDTO,

    /**
     * The BuyFromShoppingCartForm model constructor.
     * @property {module:model/BuyFromShoppingCartForm}
     */
    BuyFromShoppingCartForm,

    /**
     * The Credentials model constructor.
     * @property {module:model/Credentials}
     */
    Credentials,

    /**
     * The InvoiceDTO model constructor.
     * @property {module:model/InvoiceDTO}
     */
    InvoiceDTO,

    /**
     * The LineItemDTO model constructor.
     * @property {module:model/LineItemDTO}
     */
    LineItemDTO,

    /**
     * The MediumDTO model constructor.
     * @property {module:model/MediumDTO}
     */
    MediumDTO,

    /**
     * The RemoveFromShoppingCartForm model constructor.
     * @property {module:model/RemoveFromShoppingCartForm}
     */
    RemoveFromShoppingCartForm,

    /**
     * The ShoppingCartDTO model constructor.
     * @property {module:model/ShoppingCartDTO}
     */
    ShoppingCartDTO,

    /**
     * The SongDTO model constructor.
     * @property {module:model/SongDTO}
     */
    SongDTO,

    /**
     * The SongDTOLength model constructor.
     * @property {module:model/SongDTOLength}
     */
    SongDTOLength,

    /**
     * The SongDTOLengthDuration model constructor.
     * @property {module:model/SongDTOLengthDuration}
     */
    SongDTOLengthDuration,

    /**
     * The SongDTOLengthUnits model constructor.
     * @property {module:model/SongDTOLengthUnits}
     */
    SongDTOLengthUnits,

    /**
     * The SupplierDTO model constructor.
     * @property {module:model/SupplierDTO}
     */
    SupplierDTO,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
