openapi: 3.0.1
info:
  title: Musicshop API
  contact:
    name: Musicshop API Support
    url: http://musicshop.com/contact
    email: techsupport@musicshop.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 3.0.1
paths:
  /article/search:
    get:
      summary: Search Articles
      description: "Search Articles by Attributes (Title, Artist)"
      operationId: searchArticlesByAttributes
      parameters:
      - name: title
        in: query
        schema:
          type: string
      - name: artist
        in: query
        schema:
          type: string
      responses:
        "200":
          description: Articles found
        "404":
          description: No Articles found
  /shoppingcart/add:
    post:
      operationId: addToShoppingCart
      parameters:
      - name: userId
        in: query
        schema:
          type: string
      - name: amount
        in: query
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          text/json:
            schema:
              $ref: '#/components/schemas/MediumDTO'
      responses:
        default:
          description: default response
          content:
            '*/*': {}
  /shoppingcart/buy:
    get:
      operationId: buyFromShoppingCart
      parameters:
      - name: userId
        in: query
        schema:
          type: string
      - name: id
        in: query
        schema:
          type: integer
          format: int32
      responses:
        default:
          description: default response
          content:
            text/json: {}
  /shoppingcart/empty:
    get:
      operationId: emptyShoppingCart
      parameters:
      - name: userId
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            '*/*': {}
  /shoppingcart/get:
    get:
      operationId: getShoppingCart
      parameters:
      - name: userId
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            text/json:
              schema:
                $ref: '#/components/schemas/ShoppingCartDTO'
  /shoppingcart/remove:
    post:
      operationId: removeFromShoppingCart
      parameters:
      - name: userId
        in: query
        schema:
          type: string
      - name: amount
        in: query
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          text/json:
            schema:
              $ref: '#/components/schemas/MediumDTO'
      responses:
        default:
          description: default response
          content:
            '*/*': {}
components:
  schemas:
    AlbumDTO:
      required:
      - artists
      - genre
      - id
      - label
      - mediums
      - musicbrainzId
      - releaseDate
      - songs
      - title
      type: object
      allOf:
      - $ref: '#/components/schemas/ArticleDTO'
      - type: object
        properties:
          mediums:
            uniqueItems: true
            type: array
            items:
              $ref: '#/components/schemas/MediumDTO'
          songs:
            uniqueItems: true
            type: array
            items:
              $ref: '#/components/schemas/SongDTO'
    ArticleDTO:
      required:
      - artists
      - genre
      - id
      - label
      - musicbrainzId
      - releaseDate
      - title
      - type
      type: object
      properties:
        genre:
          type: string
        artists:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/ArtistDTO'
        title:
          type: string
        releaseDate:
          type: string
          format: date
        musicbrainzId:
          type: string
        id:
          type: integer
          format: int64
        label:
          type: string
        type:
          type: string
      discriminator:
        propertyName: type
    ArtistDTO:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    MediumDTO:
      required:
      - id
      - price
      - stockQuantity
      - supplier
      - type
      type: object
      properties:
        id:
          type: integer
          format: int64
        price:
          type: number
        type:
          type: string
        supplier:
          $ref: '#/components/schemas/SupplierDTO'
        stockQuantity:
          type: integer
          format: int32
    SongDTO:
      required:
      - albums
      - artists
      - genre
      - id
      - label
      - length
      - musicbrainzId
      - releaseDate
      - title
      type: object
      allOf:
      - $ref: '#/components/schemas/ArticleDTO'
      - type: object
        properties:
          length:
            type: object
            properties:
              seconds:
                type: integer
                format: int64
              nano:
                type: integer
                format: int32
              negative:
                type: boolean
              zero:
                type: boolean
              units:
                type: array
                items:
                  type: object
                  properties:
                    duration:
                      type: object
                      properties:
                        seconds:
                          type: integer
                          format: int64
                        nano:
                          type: integer
                          format: int32
                        negative:
                          type: boolean
                        zero:
                          type: boolean
                    durationEstimated:
                      type: boolean
                    dateBased:
                      type: boolean
                    timeBased:
                      type: boolean
          albums:
            uniqueItems: true
            type: array
            items:
              $ref: '#/components/schemas/AlbumDTO'
    SupplierDTO:
      required:
      - id
      - name
      - supplyDuration
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        supplyDuration:
          type: object
          properties:
            seconds:
              type: integer
              format: int64
            nano:
              type: integer
              format: int32
            negative:
              type: boolean
            zero:
              type: boolean
            units:
              type: array
              items:
                type: object
                properties:
                  duration:
                    type: object
                    properties:
                      seconds:
                        type: integer
                        format: int64
                      nano:
                        type: integer
                        format: int32
                      negative:
                        type: boolean
                      zero:
                        type: boolean
                  durationEstimated:
                    type: boolean
                  dateBased:
                    type: boolean
                  timeBased:
                    type: boolean
    ShoppingCartDTO:
      type: object
