/*
 * Musicshop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.1
 * Contact: techsupport@musicshop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AddToShoppingCartForm model module.
 * @module model/AddToShoppingCartForm
 * @version 3.0.1
 */
export class AddToShoppingCartForm {
  /**
   * Constructs a new <code>AddToShoppingCartForm</code>.
   * @alias module:model/AddToShoppingCartForm
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AddToShoppingCartForm</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AddToShoppingCartForm} obj Optional instance to populate.
   * @return {module:model/AddToShoppingCartForm} The populated <code>AddToShoppingCartForm</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AddToShoppingCartForm();
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
      if (data.hasOwnProperty('mediumId'))
        obj.mediumId = ApiClient.convertToType(data['mediumId'], 'Number');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} userId
 */
AddToShoppingCartForm.prototype.userId = undefined;

/**
 * @member {Number} mediumId
 */
AddToShoppingCartForm.prototype.mediumId = undefined;

/**
 * @member {Number} amount
 */
AddToShoppingCartForm.prototype.amount = undefined;

