/*
 * Musicshop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.1
 * Contact: techsupport@musicshop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ArtistDTO} from './ArtistDTO';

/**
 * The ArticleDTO model module.
 * @module model/ArticleDTO
 * @version 3.0.1
 */
export class ArticleDTO {
  /**
   * Constructs a new <code>ArticleDTO</code>.
   * @alias module:model/ArticleDTO
   * @class
   * @param genre {String} 
   * @param artists {Array.<module:model/ArtistDTO>} 
   * @param title {String} 
   * @param releaseDate {Date} 
   * @param musicbrainzId {String} 
   * @param label {String} 
   * @param id {Number} 
   * @param type {String} 
   */
  constructor(genre, artists, title, releaseDate, musicbrainzId, label, id, type) {
    this.genre = genre;
    this.artists = artists;
    this.title = title;
    this.releaseDate = releaseDate;
    this.musicbrainzId = musicbrainzId;
    this.label = label;
    this.id = id;
    this.type = type;
  }

  /**
   * Constructs a <code>ArticleDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ArticleDTO} obj Optional instance to populate.
   * @return {module:model/ArticleDTO} The populated <code>ArticleDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ArticleDTO();
      if (data.hasOwnProperty('genre'))
        obj.genre = ApiClient.convertToType(data['genre'], 'String');
      if (data.hasOwnProperty('artists'))
        obj.artists = ApiClient.convertToType(data['artists'], [ArtistDTO]);
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('releaseDate'))
        obj.releaseDate = ApiClient.convertToType(data['releaseDate'], 'Date');
      if (data.hasOwnProperty('musicbrainzId'))
        obj.musicbrainzId = ApiClient.convertToType(data['musicbrainzId'], 'String');
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} genre
 */
ArticleDTO.prototype.genre = undefined;

/**
 * @member {Array.<module:model/ArtistDTO>} artists
 */
ArticleDTO.prototype.artists = undefined;

/**
 * @member {String} title
 */
ArticleDTO.prototype.title = undefined;

/**
 * @member {Date} releaseDate
 */
ArticleDTO.prototype.releaseDate = undefined;

/**
 * @member {String} musicbrainzId
 */
ArticleDTO.prototype.musicbrainzId = undefined;

/**
 * @member {String} label
 */
ArticleDTO.prototype.label = undefined;

/**
 * @member {Number} id
 */
ArticleDTO.prototype.id = undefined;

/**
 * @member {String} type
 */
ArticleDTO.prototype.type = undefined;

