/*
 * Musicshop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.1
 * Contact: techsupport@musicshop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The BuyFromShoppingCartForm model module.
 * @module model/BuyFromShoppingCartForm
 * @version 3.0.1
 */
export class BuyFromShoppingCartForm {
  /**
   * Constructs a new <code>BuyFromShoppingCartForm</code>.
   * @alias module:model/BuyFromShoppingCartForm
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>BuyFromShoppingCartForm</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BuyFromShoppingCartForm} obj Optional instance to populate.
   * @return {module:model/BuyFromShoppingCartForm} The populated <code>BuyFromShoppingCartForm</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BuyFromShoppingCartForm();
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
      if (data.hasOwnProperty('customerId'))
        obj.customerId = ApiClient.convertToType(data['customerId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} userId
 */
BuyFromShoppingCartForm.prototype.userId = undefined;

/**
 * @member {Number} customerId
 */
BuyFromShoppingCartForm.prototype.customerId = undefined;

