/*
 * Musicshop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.1
 * Contact: techsupport@musicshop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The EmptyShoppingCartForm model module.
 * @module model/EmptyShoppingCartForm
 * @version 3.0.1
 */
export class EmptyShoppingCartForm {
  /**
   * Constructs a new <code>EmptyShoppingCartForm</code>.
   * @alias module:model/EmptyShoppingCartForm
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>EmptyShoppingCartForm</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EmptyShoppingCartForm} obj Optional instance to populate.
   * @return {module:model/EmptyShoppingCartForm} The populated <code>EmptyShoppingCartForm</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EmptyShoppingCartForm();
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} userId
 */
EmptyShoppingCartForm.prototype.userId = undefined;

