/*
 * Musicshop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.1
 * Contact: techsupport@musicshop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {LineItemDTO} from './LineItemDTO';

/**
 * The InvoiceDTO model module.
 * @module model/InvoiceDTO
 * @version 3.0.1
 */
export class InvoiceDTO {
  /**
   * Constructs a new <code>InvoiceDTO</code>.
   * @alias module:model/InvoiceDTO
   * @class
   * @param id {Number} 
   * @param lineItems {Array.<module:model/LineItemDTO>} 
   * @param totalPrice {Number} 
   * @param customerNo {Number} 
   */
  constructor(id, lineItems, totalPrice, customerNo) {
    this.id = id;
    this.lineItems = lineItems;
    this.totalPrice = totalPrice;
    this.customerNo = customerNo;
  }

  /**
   * Constructs a <code>InvoiceDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InvoiceDTO} obj Optional instance to populate.
   * @return {module:model/InvoiceDTO} The populated <code>InvoiceDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InvoiceDTO();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('lineItems'))
        obj.lineItems = ApiClient.convertToType(data['lineItems'], [LineItemDTO]);
      if (data.hasOwnProperty('totalPrice'))
        obj.totalPrice = ApiClient.convertToType(data['totalPrice'], 'Number');
      if (data.hasOwnProperty('customerNo'))
        obj.customerNo = ApiClient.convertToType(data['customerNo'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
InvoiceDTO.prototype.id = undefined;

/**
 * @member {Array.<module:model/LineItemDTO>} lineItems
 */
InvoiceDTO.prototype.lineItems = undefined;

/**
 * @member {Number} totalPrice
 */
InvoiceDTO.prototype.totalPrice = undefined;

/**
 * @member {Number} customerNo
 */
InvoiceDTO.prototype.customerNo = undefined;

