/*
 * Musicshop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.1
 * Contact: techsupport@musicshop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ArticleDTO} from './ArticleDTO';
import {MediumDTO} from './MediumDTO';

/**
 * The LineItemDTO model module.
 * @module model/LineItemDTO
 * @version 3.0.1
 */
export class LineItemDTO {
  /**
   * Constructs a new <code>LineItemDTO</code>.
   * @alias module:model/LineItemDTO
   * @class
   * @param id {Number} 
   * @param article {module:model/ArticleDTO} 
   * @param quantity {Number} 
   * @param quantityReturn {Number} 
   * @param price {Number} 
   * @param totalPrice {Number} 
   * @param medium {module:model/MediumDTO} 
   */
  constructor(id, article, quantity, quantityReturn, price, totalPrice, medium) {
    this.id = id;
    this.article = article;
    this.quantity = quantity;
    this.quantityReturn = quantityReturn;
    this.price = price;
    this.totalPrice = totalPrice;
    this.medium = medium;
  }

  /**
   * Constructs a <code>LineItemDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LineItemDTO} obj Optional instance to populate.
   * @return {module:model/LineItemDTO} The populated <code>LineItemDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LineItemDTO();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('article'))
        obj.article = ArticleDTO.constructFromObject(data['article']);
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'Number');
      if (data.hasOwnProperty('quantityReturn'))
        obj.quantityReturn = ApiClient.convertToType(data['quantityReturn'], 'Number');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'Number');
      if (data.hasOwnProperty('totalPrice'))
        obj.totalPrice = ApiClient.convertToType(data['totalPrice'], 'Number');
      if (data.hasOwnProperty('medium'))
        obj.medium = MediumDTO.constructFromObject(data['medium']);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
LineItemDTO.prototype.id = undefined;

/**
 * @member {module:model/ArticleDTO} article
 */
LineItemDTO.prototype.article = undefined;

/**
 * @member {Number} quantity
 */
LineItemDTO.prototype.quantity = undefined;

/**
 * @member {Number} quantityReturn
 */
LineItemDTO.prototype.quantityReturn = undefined;

/**
 * @member {Number} price
 */
LineItemDTO.prototype.price = undefined;

/**
 * @member {Number} totalPrice
 */
LineItemDTO.prototype.totalPrice = undefined;

/**
 * @member {module:model/MediumDTO} medium
 */
LineItemDTO.prototype.medium = undefined;

