/*
 * Musicshop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.1
 * Contact: techsupport@musicshop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {SupplierDTO} from './SupplierDTO';

/**
 * The MediumDTO model module.
 * @module model/MediumDTO
 * @version 3.0.1
 */
export class MediumDTO {
  /**
   * Constructs a new <code>MediumDTO</code>.
   * @alias module:model/MediumDTO
   * @class
   * @param id {Number} 
   * @param price {Number} 
   * @param type {String} 
   * @param supplier {module:model/SupplierDTO} 
   * @param stockQuantity {Number} 
   */
  constructor(id, price, type, supplier, stockQuantity) {
    this.id = id;
    this.price = price;
    this.type = type;
    this.supplier = supplier;
    this.stockQuantity = stockQuantity;
  }

  /**
   * Constructs a <code>MediumDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MediumDTO} obj Optional instance to populate.
   * @return {module:model/MediumDTO} The populated <code>MediumDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MediumDTO();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'Number');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('supplier'))
        obj.supplier = SupplierDTO.constructFromObject(data['supplier']);
      if (data.hasOwnProperty('stockQuantity'))
        obj.stockQuantity = ApiClient.convertToType(data['stockQuantity'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
MediumDTO.prototype.id = undefined;

/**
 * @member {Number} price
 */
MediumDTO.prototype.price = undefined;

/**
 * @member {String} type
 */
MediumDTO.prototype.type = undefined;

/**
 * @member {module:model/SupplierDTO} supplier
 */
MediumDTO.prototype.supplier = undefined;

/**
 * @member {Number} stockQuantity
 */
MediumDTO.prototype.stockQuantity = undefined;

