/*
 * Musicshop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.1
 * Contact: techsupport@musicshop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {LineItemDTO} from './LineItemDTO';

/**
 * The ShoppingCartDTO model module.
 * @module model/ShoppingCartDTO
 * @version 3.0.1
 */
export class ShoppingCartDTO {
  /**
   * Constructs a new <code>ShoppingCartDTO</code>.
   * @alias module:model/ShoppingCartDTO
   * @class
   * @param lineItems {Array.<module:model/LineItemDTO>} 
   * @param totalAmount {Number} 
   */
  constructor(lineItems, totalAmount) {
    this.lineItems = lineItems;
    this.totalAmount = totalAmount;
  }

  /**
   * Constructs a <code>ShoppingCartDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ShoppingCartDTO} obj Optional instance to populate.
   * @return {module:model/ShoppingCartDTO} The populated <code>ShoppingCartDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ShoppingCartDTO();
      if (data.hasOwnProperty('lineItems'))
        obj.lineItems = ApiClient.convertToType(data['lineItems'], [LineItemDTO]);
      if (data.hasOwnProperty('totalAmount'))
        obj.totalAmount = ApiClient.convertToType(data['totalAmount'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/LineItemDTO>} lineItems
 */
ShoppingCartDTO.prototype.lineItems = undefined;

/**
 * @member {Number} totalAmount
 */
ShoppingCartDTO.prototype.totalAmount = undefined;

