/*
 * Musicshop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.1
 * Contact: techsupport@musicshop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {SongDTOLengthUnits} from './SongDTOLengthUnits';

/**
 * The SongDTOLength model module.
 * @module model/SongDTOLength
 * @version 3.0.1
 */
export class SongDTOLength {
  /**
   * Constructs a new <code>SongDTOLength</code>.
   * @alias module:model/SongDTOLength
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SongDTOLength</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SongDTOLength} obj Optional instance to populate.
   * @return {module:model/SongDTOLength} The populated <code>SongDTOLength</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SongDTOLength();
      if (data.hasOwnProperty('seconds'))
        obj.seconds = ApiClient.convertToType(data['seconds'], 'Number');
      if (data.hasOwnProperty('nano'))
        obj.nano = ApiClient.convertToType(data['nano'], 'Number');
      if (data.hasOwnProperty('units'))
        obj.units = ApiClient.convertToType(data['units'], [SongDTOLengthUnits]);
      if (data.hasOwnProperty('negative'))
        obj.negative = ApiClient.convertToType(data['negative'], 'Boolean');
      if (data.hasOwnProperty('zero'))
        obj.zero = ApiClient.convertToType(data['zero'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Number} seconds
 */
SongDTOLength.prototype.seconds = undefined;

/**
 * @member {Number} nano
 */
SongDTOLength.prototype.nano = undefined;

/**
 * @member {Array.<module:model/SongDTOLengthUnits>} units
 */
SongDTOLength.prototype.units = undefined;

/**
 * @member {Boolean} negative
 */
SongDTOLength.prototype.negative = undefined;

/**
 * @member {Boolean} zero
 */
SongDTOLength.prototype.zero = undefined;

