/*
 * Musicshop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.1
 * Contact: techsupport@musicshop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {SongDTOLength} from './SongDTOLength';

/**
 * The SupplierDTO model module.
 * @module model/SupplierDTO
 * @version 3.0.1
 */
export class SupplierDTO {
  /**
   * Constructs a new <code>SupplierDTO</code>.
   * @alias module:model/SupplierDTO
   * @class
   * @param id {Number} 
   * @param name {String} 
   * @param supplyDuration {module:model/SongDTOLength} 
   */
  constructor(id, name, supplyDuration) {
    this.id = id;
    this.name = name;
    this.supplyDuration = supplyDuration;
  }

  /**
   * Constructs a <code>SupplierDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SupplierDTO} obj Optional instance to populate.
   * @return {module:model/SupplierDTO} The populated <code>SupplierDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SupplierDTO();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('supplyDuration'))
        obj.supplyDuration = SongDTOLength.constructFromObject(data['supplyDuration']);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
SupplierDTO.prototype.id = undefined;

/**
 * @member {String} name
 */
SupplierDTO.prototype.name = undefined;

/**
 * @member {module:model/SongDTOLength} supplyDuration
 */
SupplierDTO.prototype.supplyDuration = undefined;

